### PR TITLE
aim: add violet to official devices

### PR DESCRIPTION
**Pull request by Joker-V2**

### CODE REVIEW

**Comment by Joker-V2** [comment]
Device tree : https://github.com/Joker-V2/device_xiaomi_violet
Branch : ten

**Comment by krasCGQ** [comment]
Can elaborate on why external QCOM HALs are required?

**Comment by Joker-V2** [comment]
Because we are using gralloc 3.0 .. only display hals needed to be external to boot the device

**Review by krasCGQ — APPROVED** [review]
DyneOEM smh

**Comment by krasCGQ** [comment]
```
くらすさん // krasCGQ – #brick4lyf, [6/15/20, 11:02 AM]
[In reply to Henrique Pereira // Read my bio]
Is it backwards compatible tho?

Like Dyne's patch won't break existing devices?

Henrique Pereira // Read my bio, [6/15/20, 11:03 AM]
[In reply to くらすさん // krasCGQ – #brick4lyf]
You'd need to uprev then for all devices that build parts of the display HAL from source

Henrique Pereira // Read my bio, [6/15/20, 11:03 AM]
Just that

Henrique Pereira // Read my bio, [6/15/20, 11:04 AM]
https://github.com/PixelExperience-Devices/device_xiaomi_violet/commit/fa8ca78b58320e6d56acdd45ef0477eb7cd778d1

Henrique Pereira // Read my bio, [6/15/20, 11:04 AM]
Or simply revert this on the tree

Henrique Pereira // Read my bio, [6/15/20, 11:05 AM]
(This is back from Nov)
```

**Comment by Joker-V2** [comment]
Ok...i will revert that on the tree if required !!

**Pull request closed without merging**
