### PR TITLE
Change Miscs to Miscellaneous

### PR DESCRIPTION
**Pull request by shirofficial**

### CODE REVIEW

**Comment by sathish2026** [comment]
@shirofficial  it would be better if u provide any screenshot of freedomhub with ur misc to miscellaneous change

**Comment by Rpingat** [comment]
@sathish2026 Yeah right

**Review by krasCGQ — COMMENTED** [review]
And does it compile correctly?

**Comment by Anandnv** [comment]
Forgot to change class in miscellaneous ..☺

**Comment by Anandnv** [comment]
Closing pull 💢

**Pull request closed without merging**
